# Generated by Django 5.1.7 on 2025-03-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogboarding',
            name='location',
        ),
        migrations.AddField(
            model_name='dogboarding',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='dogboarding',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
